///|
let screen_w : Int = 1720

///|
let screen_h : Int = 980

///|
let target_fps : Int = 120

///|
let max_board : Int = 12

///|
let max_cells : Int = max_board * max_board

///|
let cell_unknown : Int = 0

///|
let cell_fill : Int = 1

///|
let cell_cross : Int = 2

///|
let state_title : Int = 0

///|
let state_play : Int = 1

///|
let state_level_clear : Int = 2

///|
let state_campaign_clear : Int = 3

///|
let state_level_fail : Int = 4

///|
let tool_fill : Int = 1

///|
let tool_cross : Int = 2

///|
let dir_none : Int = 0

///|
let dir_left : Int = 1

///|
let dir_right : Int = 2

///|
let dir_up : Int = 3

///|
let dir_down : Int = 4
